version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./auth_service/migrations:/docker-entrypoint-initdb.d
      - ./auth_service/postgres_volume:/var/lib/postgresql
    networks:
      - fullstack
  nats:
    image: 'bitnami/nats:latest'
    container_name: nats_server
    expose:
      - "4222"
    networks:
      - fullstack
    environment:
      - HOST=nats_server
  auth_service:
    container_name: auth_service
    build: 
      context: ./auth_service
      dockerfile: Dockerfile.dev
    volumes:
      - ./auth_service:/auth_s
    restart: on-failure
    depends_on:
      - postgres
      - nats
    links:
      - nats
    networks:
      - fullstack
    env_file:
      - ./auth_service/.env
    environment:
      - HOST=auth_service
      - DB_HOST=postgres
      - NATS_HOST=nats_server
  auth_api:
    container_name: auth_client
    build: 
      context: ./auth_client
      dockerfile: Dockerfile.dev
    ports:
      - "8082:8082"
    volumes:
    - ./auth_client:/auth_c
    restart: on-failure
    depends_on:
      - auth_service
    networks:
      - fullstack
    env_file:
      - ./auth_client/.env
    environment:
      - AUTH_HOST=auth_service
  logger:
    container_name: logger_client
    build: ./logger_client
    restart: on-failure
    depends_on:
      - auth_service
    networks:
      - fullstack
    env_file:
      - ./logger_client/.env
    environment:
      - AUTH_HOST=auth_service
  mail_service:
    container_name: mail_service
    #build: ./mail_service
    build: 
      context: ./mail_service
      dockerfile: Dockerfile.dev
    volumes:
      - ./mail_service:/mail_s
    restart: on-failure
    depends_on:
      - nats
      - auth_service
    links:
      - nats
    networks:
      - fullstack
    env_file:
      - ./mail_service/.env
    environment:
      - NATS_HOST=nats_server
networks:
  fullstack:
    driver: bridge